### PR TITLE
102 AddDish Command exception handling v1.1

### LINKED ISSUE #102: Correct exception handling for prepareAdd function

### PR DESCRIPTION
**Pull request by DextheChik3n**
Fixes #102.

### CODE REVIEW

File: src/main/java/seedu/cafectrl/parser/Parser.java [hunk 1]
```diff
@@ -130,49 +130,42 @@ private static Command prepareAdd(String arguments) {
...
+            checkNegativePrice(price);
 
             // Capture the list of ingredients
             ArrayList<Ingredient> ingredients = new ArrayList<>();
 
-            IncorrectCommand incorrectCommand2 = ingredientParsing(ingredientsListString, ingredients);
-            if (incorrectCommand2 != null) {
-                return incorrectCommand2;
-            }
+            ingredientParsing(ingredientsListString, ingredients);
```
Comment (ziyi105) [inline src/main/java/seedu/cafectrl/parser/Parser.java:150]: Perhaps you could make it return the modified ingredients as it would be useful for JUnit test and debugging in the future

**Review by ziyi105 — CHANGES_REQUESTED** [review]
Overall good

File: src/main/java/seedu/cafectrl/parser/Parser.java (hunk 1 above)
Comment (DextheChik3n) [reply src/main/java/seedu/cafectrl/parser/Parser.java]: ok that is a good idea! I have already made the changes

**Review by ziyi105 — APPROVED** [review]
LGTM
