### PR TITLE
Bug fix hash string tampered with large number

### LINKED ISSUE #328: Error thrown when loading empty menu file
image
To recreate this error:  run the app with existing but empty orders and menu text file, one line: chicken | 800 | g  in pantrystock

### PR DESCRIPTION
**Pull request by Cazh1**
Fixes #328

### CODE REVIEW

File: src/main/java/seedu/cafectrl/storage/Storage.java [hunk 1]
```diff
@@ -35,6 +36,14 @@ public Storage (Ui ui) {
     }
 
     //@@author Cazh1
+
+    private boolean isFileEmpty(ArrayList<String> encodedStringArrayList) {
+        if (encodedStringArrayList.isEmpty()) {
+            return true;
+        }
+        return false;
```
Comment (ShaniceTang) [inline src/main/java/seedu/cafectrl/storage/Storage.java:44]: Would it be better to write this as a single line?
```suggestion
        return encodedStringArrayList.isEmpty();
```

**Review by ShaniceTang — APPROVED** [review]
Looks good!
