### PR TITLE
Fix minor bugs for several features

### LINKED ISSUE #365: buy_ingredient unusual output for very large quantity
image

### LINKED ISSUE #367: buy_ingredient: change Qty to Total quantity for better clarification
image

Was thinking the output shown above could confuse the user, as they could interpret it as "added 200g of rice to stock", when 200 is the total quantity and they only added 100g of rice

### LINKED ISSUE #368: delete command: wrong error message for wrong dish index type
image

Perhaps you could simply add instruction on how to use the command so that the error msg is more generalised, e.g., Error: missing arguments for delete comand\n the correct format for delete command is...

### LINKED ISSUE #372: Wrong ingredient name case for view_stock
image

I buy RICE first and followed by rice, but in view_stock the ingredient name is still RICE, should we convert everything to lowercase in view_stock?

### LINKED ISSUE #377: Menu Decoder: able to add a negative price dish from menu.txt
image

### LINKED ISSUE #378: Menu decoder: large price number in menu.txt causes price in list_menu to display "?"
After editing the menu.txt for the price of the dish to be a very large number:
image

Exiting the application after that causes the price of the dish in the text file to be Infinity:
image

### PR DESCRIPTION
**Pull request by ShaniceTang**
Buy Ingredient
- Fixes #365
- Fixes #367

View Total Stock
- Fixes #372

Delete
- Fixes #368

Menu Decoder
- Fixes #377
- Fixes #378

### CODE REVIEW

File: src/main/java/seedu/cafectrl/parser/Parser.java [hunk 1]
```diff
@@ -72,11 +72,12 @@ public class Parser implements ParserUtil {
...
     /** The rest of Command Handler Patterns*/
+
     private static final String LIST_INGREDIENTS_ARGUMENT_STRING = "dish/(.+)";
-    private static final String DELETE_ARGUMENT_STRING = "(\\d+)";
+    private static final String DELETE_ARGUMENT_STRING = "(.+)";
     private static final String EDIT_PRICE_ARGUMENT_STRING = "dish/(.*)\\sprice/(.*)";
-    private static final String BUY_INGREDIENT_ARGUMENT_STRING = "(ingredient/[A-Za-z0-9\\s]+ qty/[A-Za-z0-9\\s]+"
-            + "(?:, ingredient/[A-Za-z0-9\\s]+ qty/[A-Za-z0-9\\s]+)*)";
+    private static final String BUY_INGREDIENT_ARGUMENT_STRING = "(ingredient/[A-Za-z0-9\\\\s]+ qty/.+"
+            + "(?:, ingredient/[A-Za-z0-9\\\\s]+ qty/.+)*)";
```
Comment (DextheChik3n) [inline src/main/java/seedu/cafectrl/parser/Parser.java:80]: perhaps you should remove the extra '\\' in the regex
```suggestion
    private static final String BUY_INGREDIENT_ARGUMENT_STRING = "(ingredient/[A-Za-z0-9\\s]+ qty/.+"
            + "(?:, ingredient/[A-Za-z0-9\\s]+ qty/.+)*)";
```

**Review by DextheChik3n — APPROVED** [review]
LGTM 👍
